import { fireEvent, render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import { ConfigGeneratorPanel } from "@/components/site/app-panels/config-generator-panel";

describe("ConfigGeneratorPanel (#6183)", () => {
  it("mounts ConfigGeneratorYamlPreview so the generated YAML is visible for an empty form", () => {
    render(<ConfigGeneratorPanel />);
    expect(screen.getByText("Preview")).toBeTruthy();
    expect(screen.getByText(/The exact/)).toBeTruthy();
    expect(screen.getAllByText(".loopover.yml").length).toBeGreaterThanOrEqual(2);
    expect(screen.getByText(/generated by the config generator/)).toBeTruthy();
  });

  it("updates the YAML preview when the AI provider mode field group changes formState", () => {
    render(<ConfigGeneratorPanel />);
    fireEvent.click(screen.getByRole("radio", { name: "consensus" }));
    expect(screen.getByText(/combine: consensus/)).toBeTruthy();
  });
});
