import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import { ConfigGeneratorYamlPreview } from "@/components/site/app-panels/config-generator-yaml-preview";
import type { GeneratorFormState } from "@/lib/config-generator-yaml";

describe("ConfigGeneratorYamlPreview", () => {
  it("renders the serialized YAML, the filename label, and a copy button for a populated form state", () => {
    const state: GeneratorFormState = {
      gate: { aiReview: { combine: "consensus", provider: "anthropic" } },
    };
    render(<ConfigGeneratorYamlPreview formState={state} />);

    expect(screen.getByText("Preview")).toBeTruthy();
    // The filename appears both in the descriptive copy and the CodeBlock's own filename label.
    expect(screen.getAllByText(".loopover.yml").length).toBeGreaterThanOrEqual(2);
    expect(screen.getByText(/combine: consensus/)).toBeTruthy();
    expect(screen.getByText(/provider: anthropic/)).toBeTruthy();
    expect(screen.getByRole("button", { name: "Copy code" })).toBeTruthy();
  });

  it("still renders a valid (header-only) preview for an empty form state", () => {
    render(<ConfigGeneratorYamlPreview formState={{}} />);
    expect(screen.getByText(/generated by the config generator/)).toBeTruthy();
    expect(screen.queryByText(/aiReview/)).toBeNull();
  });
});
