// Config-generator YAML preview serializer (#2210, part of #1683). Pure form-state -> `.loopover.yml`
// text builder — the reviewable-output half of the config generator; field-group panels (#2208 and
// siblings) own collecting GeneratorFormState, this module only turns it into text. Key names and
// nesting match the real manifest schema (packages/gittensory-engine/src/focus-manifest.ts's
// gateConfigToJson `gate.aiReview` shape, the same shape documented in this repo's own root
// .loopover.yml under the commented-out `aiReview:` example) — no parallel schema. Every field is
// optional so a fresh/partial form never produces invalid output; unset keys are omitted entirely.
// The generated header names the `.loopover.yml` filename.

export type AiCombineStrategy = "single" | "consensus" | "synthesis";
export type AiProvider = "anthropic" | "openai";

export type GeneratorGateAiReviewState = {
  combine?: AiCombineStrategy | null;
  provider?: AiProvider | null;
  model?: string | null;
};

export type GeneratorFormState = {
  gate?: {
    aiReview?: GeneratorGateAiReviewState;
  };
};

const YAML_HEADER = "# .loopover.yml — generated by the config generator";

/** Plain-scalar YAML value needs quoting when it would otherwise be ambiguous (a YAML special
 *  character, leading/trailing whitespace, or the empty string). Model names are free text, so this
 *  is a real correctness need, not defensive-for-its-own-sake. */
function yamlScalar(value: string): string {
  const needsQuote = value === "" || value.trim() !== value || /[:#[\]{}&*!|>'"%@`,]/.test(value);
  return needsQuote ? JSON.stringify(value) : value;
}

function yamlLine(indent: number, key: string, value: string): string {
  return `${"  ".repeat(indent)}${key}: ${yamlScalar(value)}`;
}

/** Serializes the `gate.aiReview` slice of GeneratorFormState into `.loopover.yml` text, omitting
 *  every unset field/block so the preview is always valid YAML (including the empty-state case). */
export function formStateToYaml(state: GeneratorFormState): string {
  const aiReview = state.gate?.aiReview;
  const aiReviewLines: string[] = [];
  if (aiReview?.combine) aiReviewLines.push(yamlLine(2, "combine", aiReview.combine));
  if (aiReview?.provider) aiReviewLines.push(yamlLine(2, "provider", aiReview.provider));
  if (aiReview?.model) aiReviewLines.push(yamlLine(2, "model", aiReview.model));

  const lines = [YAML_HEADER];
  if (aiReviewLines.length > 0) {
    lines.push("gate:", "  aiReview:", ...aiReviewLines);
  }
  return lines.join("\n");
}
